version: "3.5"
services:
  web:
    build: TravellingBackend/TravellingApp.Api/
    image: travelling-web
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development=Production
  frontend:
    build: TravellingFrontend/
    image: travelling-frontend
    ports:
      - 5173:5173
    depends_on:
      - web
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
